language: node_js
deploy:
  provider: s3
  access_key_id: "AKIATYNDKXNGODLHQ45L"
  secret_access_key:
    secure: "YUmY9FnCj7Smjndu6pVKONSkQOWs89Qw3WvUVQd/Pm+HCg+8PZqx+5XS72bcd1zk9idlLo7urlMI+jKo13G6K5Y1GOJ4/XKKFbVXP5mAOO/XqwcGu+ynZl19Jq7stskoGe+BdBqdK41M+aCx8QejlQz4ncSXHsH88x4OjpyDt3JngvJUvVWtHSNC522jfaAE9D1Jy0DVwEjMQk88fi+EczVEfzF3fNaBSFE8B/9N9DTHHqAj/1M18tK6fBApFAG7k1e3P0fkr38+hp7YTV9kPEbvjO85Y3pe/7tIi5zE+aIQYyhCSWGAAnQd2WinZA4v5Qn0/A6/sdvkqdQYMiz0bDDTPYQ5pDQ2kODi8tb3bkGWv5onah7Sf27DDCFHAlWfv/g4O/XnvKrdSROsZScNefskg3Tdih2ixXeyzLLlDMZfFx5Gw8QayZ1MoGjEAN0CKDo8UoVcJbAXyIm1dbnYVxE25l3Xz0zIBB0+OYT5zjMf9gWA90oFI3kfNulutL8o+BB5LWeC6EgffW+75Lj+mtOWEOA+FLqIqb/6oKMNbnPrtVP9W9MCpNL5tj5Jd+fytQZWFXo8TDsRltTsuaBQbQm0vxzIkpZQMDzzL4X/ZGYztozlsFqLeVPbtUcCZTxkZw8rCK59zNfNyioaDjK1COQ0uSwef9T89xJNOhdBlCk="
  bucket: taal-cdn
  skip_cleanup: true
  region: eu-west-1
  upload-dir: oss/test
